### ISSUE TITLE
Status code on validation error

### ISSUE THREAD

**Issue by lefloh** [chkal/todo-mvc#2]
The TodoListController is returning the status code 200 if validation fails. Wouldn't you rather return a 400 in this case?

**Comment by chkal** [comment]
I think most web frameworks use 200 OK even if rendering validation error messages. That's how JSF, Struts and others work. For REST APIs 400 makes more sense of cause.

AFAIK some browsers implement some weird behavior for 4xx codes like:

> If the servers responds with 4xx and the content length is < X, show a browser generated "Something went wrong" page.

**Comment by lefloh** [comment]
JSF definitely does but I thought MCV should work closer on HTTP? At least Play suggests something different [in their documentation](https://www.playframework.com/documentation/2.0/JavaActions#Results).
Also if you don't have a REST API you would not return a 200 if a resource is not found (unless you don't care finding this page in the google index), would you?

**Comment by chkal** [comment]
Sure, but I'm even not sure if 400 is the correct status code for failed form validation:

> 400 Bad Request: The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Is an invalid email address entered into a form field really a "client error" or "malformed request syntax"? Looks like this status codes describes lower level problems.

Also, as an application developer I would prefer to use 200 instead of 400 to work around problems like:

http://support.microsoft.com/kb/294807

However, perhaps there should be an easy way for developers to choose the status code used even for standard page rendering? Feel free to suggest this on the JSR users list. Would be interesting to hear other opinions about that.

https://java.net/projects/mvc-spec/lists

**Comment by lefloh** [comment]
I really like it when Microsoft is redirecting me to the German Translation of their KnowledgeBase :)

> Wie Internet Explorer deaktivieren "Zeigen kurze HTTP-Fehlermeldungen" auf dem Server verfügen

I don't know why Microsoft decided that everything greater 512 byte is a error message worth showing to the client whereas everything smaller is not. But I think in most cases (if I return a form with validation errors) I won't face that problem or would rather [choose a different workaround](http://stackoverflow.com/a/11544049) than changing the semantic of my HTTP Response.

I don't think there's really a correct validation error status code. Some people use 400, some 422, some even 401 or 403. I follow [this answer on stackoverflow](http://stackoverflow.com/a/3290198).

I'm fine with MVC returning a 200 as default (as apparently some/many developers prefer this one ;). MVC already provides an easy way to change the status code quite similar to play:

```
 return Response.status(401).entity("items.jsp").build();
```

I'd implement it this way but as your 200 is intentional I'll close this issue.

**Comment by chkal** [comment]
Okay. Great. Anyway, thanks a lot for your feedback. ANY kind of feedback is welcome to improve the JSR.
